id: I075C5FDC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T22:37:42+00:00'
last_modified: '2022-06-08T12:43:58.411006+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB13635
  title: གཙང་སྟོད་ཟིན་ཐིག་དང་ཡང་ཐིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B810:
      image_group_id: I1PD30941
      title: Volume 1 of gtsang stod zin thig dang yang thig
      total_pages: 710
      order: 1
      base_file: B810.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
