id: P006940
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:54.684705
source_metadata:
  id: bdr:W2DB13635
  title: གཙང་སྟོད་ཟིན་ཐིག་དང་ཡང་ཐིག
  author: ''
  volumes:
    5bd41102ddf343029230aff15e8b1f38:
      image_group_id: I1PD30941
      title: Volume 1 of gtsang stod zin thig dang yang thig
      volume_number: 1
      total_pages: 710
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
