id: P006940
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB13635
  title: གཙང་སྟོད་ཟིན་ཐིག་དང་ཡང་ཐིག
  author: ''
  volumes:
    4c3cb224c6584b25a4b0e6482da2caac:
      image_group_id: I1PD30941
      title: ''
      volume_number: 1
      total_pages: 710
ebook_metadata:
  title: གཙང་སྟོད་ཟིན་ཐིག་དང་ཡང་ཐིག
  author: ''
  sku: P006940
  cover: cover.jpg
  layers:
  - pagination
